### ISSUE TITLE
Thoughts on "A response too big for the comments section"

### ISSUE THREAD

**Issue by christopherallanperry** [micahgodbolt/micahcodes#1]
Just for a bit of background, I work in an IT dept in the aerospace industry as a project manager. Largely I deliver infrastructure (servers, networks, comms), with relatively little direct involvement in the development of solutions, though I did start in a development role on our first intranet over 16 years ago. Because I work outside the 'web industry', my views are likely to come from a place that has a slightly different mental model to some of the ideas expressed.

"For a Frontend Designer the creative effort is not measured by the visual appearance of our end product, but by the processes we employ in producing said product." [ref to also include bullets below this text].

In my mind, design is a larger concept than the purely visual. Design solves problems, no more, no less. From what I see, the web industry seems to have equated 'design' with 'visual' as you allude to. Whether that's come from the use of PS to make mock-ups, because it's a contraction of 'graphic design', or whether the world has become enamoured of the slick aesthetics associated with Apple I don't know. What design should revolve around is process, functionality, supportability, accessibility (you mentioned), durability, safety, reliability, and ease of use. Without those, an attractive countenance devolves itself in window dressing. I think you get that, but I'm not sure 'web world' has evolved or structured itself around the same sort of engineered approach to them that I get to see where I am.

"For every second we spend completing a develoment task, we spend an equal amount of time designing solutions for the unique problems we face in our profession."

Typo: 'development'

"Sure, I don't have any problem calling ourselves Frontend Developers instead, but we do ourselves a disservice to ignore the fact that we are all designers in our own way."

Absolutely agree

"...we all live in " a sort of purgatory between worlds"."

I wonder if that is a sign of the relative youth of web development? Other industries rely on professional bodies, ISO and other standards to define themselves, where web points at individuals like Jeffrey Zeldman, Eric Meyer, Ethan Marcotte and others to set a direction. Web is very fast moving and hard to pin down, and it seem job titles follow suit. In some ways the title matters little so long as you can be reasonably clear on what the role is expected to achieve.

"But think about the other roles of your organization, and ask yourself how much does your lawyer know about marketing best practices"

Possibly not marketing, but they probably do need to know how to prepare a budget, deal with staff issues, have a grasp of procurement processes, and contribute to their company strategy amongst others. For me, 'project manager' may as well mean 'jack of all trades', and I'm not sure that's all that uncommon.

"Therefore, I wholeheartedly join brad in embracing the ambiguity of our role. I revel in the fact that we, as Frontend Designers, are not just allowed, but encouraged to reach as far up and down the stack as we desire."

And that I think is how we grow into a bigger pair of shoes. You learn by stepping out of the comfort zone, and that's the adrenaline gets you going.

"Taking up the torch" & "Raising a Banner for Frontend Architeture"

I think this is where the piece really finds its voice, where the preceding sections seem slightly unsure about themselves and their place. I wonder whether you could signal that voice right up front - let the reader know where you're going.

"Conclusion"

Typo: 1st paragraph, 1st word - 'whether'

"Our project succeeds when the visual design of the site inspires and delights, while at the same time the design system is able to scale effortlessly without placing a burden on development or infrastructure."

Referring back to my earlier point, design succeeds when it solves problems (and preferably without adding any new ones).

I hope this adds something for you to consider. I am actually looking forward to seeing your book in print, it sounds like it ought to be an important contribution to the future of the way in which the web moves forward.

**Comment by micahgodbolt** [comment]
Thanks for the great feedback @ChrisofArabia! It's always beneficial to get the opinion of someone a bit outside the circle of my primary audience. I've fixed the few typos, but am not sure if there is a way for me to draw further attention to the "taking up the torch" section without taking the focus off what this article is about: a response to brads article. 

I'm glad my dissecting of our industries use of "designer" resonated with you. I completely agree that the term "design" has been overly associated with visual designers. This is probably an artifact of the fact that many web development departments used to do traditional print media where visual design was really the only design. 

And now that I write all of that, maybe I need to get that paragraph into the article!

**Comment by micahgodbolt** [comment]
Woo! Your comments made it into the article. I didn't quote you directly, just said "friend". Happy to give you some attribution, or point to this issue if you would like credit.

**Comment by christopherallanperry** [comment]
Micah,

I just saw your response this morning. I'm just glad that I'd not gone off on completely the wrong tack - I probably wrote far more than I really needed in this instance, but it's probably one of those topics where I could go off and write my own blog post on the subject. Anyway, good to see it helped you crystallise you own thoughts. I'm more than happy with the mention as it stands.

Chris
